name: Python File Writter CI
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set Up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13' 
            
            - name: Install Depenedcies
              run: pip install pytest

            - name: Run Test Cases
              run: pytest