name: Print Commit Message
on:
    push:
        branches:
            - 'master'
            # - '**'   #run when you push on any branch
jobs:
    print-message:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Print Message
              run: |
                echo "Commit message:"
                git log -1 --pretty=%B

